#!/usr/bin/env bash

# import devos library.
#curl https://raw.githubusercontent.com/vandenberghinc/devos/master/lib/import | bash 
rm -fr /tmp/import && curl https://raw.githubusercontent.com/vandenberghinc/devos/master/lib/import -o /tmp/import && chmod +x /tmp/import && bash /tmp/import

# the alias.
alias="ssht00ls"

# the source name.
source_name=$alias

# the pypi package name (may differ from alias).
pypi_name=$alias

# boolean indicating whether the package is an pypi package.
pypi_package="true"

# boolean indicating whether to create a syst3m alias.
create_alias="true"

# pip requirements file (subpath) (leave "none" to ignore).
pip_requirements="/requirements/requirements.pip"

# apt requirements file (subpath) (leave "none" to ignore).
apt_requirements="/requirements/requirements.apt"

# brew requirements file (subpath) (leave "none" to ignore).
brew_requirements="/requirements/requirements.brew"

# install the source code to a lib path (leave "none" to ignore).
lib="/usr/local/lib/$alias/" 

# create an database directory (leave "none" to ignore).
database="/etc/$alias/" 

# defaults.
source=$(source-path $(requirements-path $0))

# execute packge installer.
install-package \
    --alias $alias \
    --source $source \
    --source-name $source_name \
    --pypi-name $pypi_name \
    --pypi-package $pypi_package \
    --create_alias $create_alias \
    --pip_requirements $pip_requirements \
    --apt_requirements $apt_requirements \
    --brew_requirements $brew_requirements \
    --lib $lib \
    --database $database \
    $@
